### ISSUE TITLE
Exporter should not require super user permissions

### ISSUE THREAD

**Issue by jesusha123** [huhamhire/air-co2-exporter#4]
## Problem

Exporter should not require super user permissions

## Steps to reproduce

- Compile and install project
  - `go get -v github.com/huhamhire/air-co2-exporter/...`
  - `cd [project_path]`
  - `go build`
  - `go install`
  - `/home/[user]/go/bin/co2-exporter`    (no sudo)
- Maybe try to get metrics through curl? I don't know how to reproduce yet.

## Logs

```
➜  ~ /home/max/go/bin/co2-exporter 
level=error ts=2020-10-19T06:42:18.128Z caller=main.go:65 err="libusb: bad access [code -3]"                                                                                                                  /0.0s
```

## System

OS: Ubuntu 20.04
GO: go version go1.14.10 linux/amd64
CO2 Monitor: CO2Meter RAD-0301 Mini CO2 Monitor

**Comment by huhamhire** [comment]
You'll need to update udev rules to work with libusb as non root user. 

https://askubuntu.com/questions/978552/how-do-i-make-libusb-work-as-non-root
